unit TilesTests;

{ FPCUnit tests for the ported uo\tiles.pas, against the synthetic fixture set in
  tests\fixtures\mul (generated by tests\tools\GenerateMulFixtures.ps1, which computes
  every offset independently from the same documented .mul format the Pascal code
  implements -- not by copying the Pascal formulas verbatim). Covers layer-0 (map)
  reads, layer>0 (statics) reads, and that GetLayerCount/GetTileData correctly filter
  by (x,y) within a shared 8x8 block rather than over-counting a neighbouring tile's
  statics. }

{$mode objfpc}{$H+}

interface

uses
  Classes, SysUtils, fpcunit, testregistry, uoclidata, tiles;

type
  TTilesTests = class(TTestCase)
  private
    Cst : TCstDB;
    T   : TTTBasic;
  protected
    procedure SetUp; override;
    procedure TearDown; override;
  published
    procedure TestLayerCountFiltersByCoordinate;
    procedure TestLayer0MapTile;
    procedure TestLayer1StaticTile;
    procedure TestLayer2StaticTile;
    procedure TestLayer0MapTileViaUopFallback;
  end;

implementation

const
  FixtureDir = 'D:\Dropbox\Delphi\EasyUOLazarus\Lazarus\tests\fixtures\mul\';
  UopFixtureDir = 'D:\Dropbox\Delphi\EasyUOLazarus\Lazarus\tests\fixtures\uop\';

procedure TTilesTests.SetUp;
begin
  Cst := TCstDB.Create;
  Cst.Update('');              // FFLAGS=0 -> landdata_size=26, tiledata_size=37,
                                // matching what GenerateMulFixtures.ps1 laid out.
  T := TTTBasic.init(FixtureDir, False, Cst);
end;

procedure TTilesTests.TearDown;
begin
  T.Free;
  Cst.Free;
end;

procedure TTilesTests.TestLayerCountFiltersByCoordinate;
var cnt : byte;
begin
  AssertTrue(T.GetLayerCount(3, 2, 0, cnt));
  AssertEquals('two statics at (3,2); the (5,5) entry must not count', 2, cnt);
end;

procedure TTilesTests.TestLayer0MapTile;
var
  tt   : word;
  z    : shortint;
  name : String;
  flags: longword;
begin
  AssertTrue(T.GetTileData(3, 2, 0, 0, tt, z, name, flags));
  AssertEquals(100, tt);
  AssertEquals(5, z);
  AssertEquals('TestLand', Trim(name));
  AssertEquals($12345678, Integer(flags));
end;

procedure TTilesTests.TestLayer1StaticTile;
var
  tt   : word;
  z    : shortint;
  name : String;
  flags: longword;
begin
  AssertTrue(T.GetTileData(3, 2, 0, 1, tt, z, name, flags));
  AssertEquals(200, tt);
  AssertEquals(10, z);
  AssertEquals('TestStatic1', Trim(name));
  AssertEquals(1, Integer(flags));
end;

procedure TTilesTests.TestLayer2StaticTile;
var
  tt   : word;
  z    : shortint;
  name : String;
  flags: longword;
begin
  AssertTrue(T.GetTileData(3, 2, 0, 2, tt, z, name, flags));
  AssertEquals(201, tt);
  AssertEquals(11, z);
  AssertEquals('TestStatic2', Trim(name));
  AssertEquals(2, Integer(flags));
end;

////////////////////////////////////////////////////////////////////////////////
// New addition (not present in the original app): tests\fixtures\uop is the same
// synthetic tile data as tests\fixtures\mul (see tests\tools\GenerateUopFixture.ps1),
// but map0.mul is repackaged into a minimal, from-scratch-built map0LegacyMUL.uop and
// NOT present at all -- exercises TTTBasic's classic-preferred/UOP-fallback path (see
// tiles.pas's own openmapfiles comment and uopfile.pas) end to end, independently of
// the real EA-install file that feature was originally validated against. Uses its own
// local TTTBasic/TCstDB rather than the shared T/Cst from SetUp, which always points at
// the classic-only fixture dir.
procedure TTilesTests.TestLayer0MapTileViaUopFallback;
var
  UopCst : TCstDB;
  UopT   : TTTBasic;
  tt     : word;
  z      : shortint;
  name   : String;
  flags  : longword;
begin
  UopCst := TCstDB.Create;
  try
    UopCst.Update('');
    UopT := TTTBasic.init(UopFixtureDir, False, UopCst);
    try
      AssertTrue('layer-0 (map) read via the UOP fallback',
        UopT.GetTileData(3, 2, 0, 0, tt, z, name, flags));
      AssertEquals(100, tt);
      AssertEquals(5, z);
      AssertEquals('TestLand', Trim(name));
      AssertEquals($12345678, Integer(flags));
    finally
      UopT.Free;
    end;
  finally
    UopCst.Free;
  end;
end;

////////////////////////////////////////////////////////////////////////////////
initialization
  RegisterTest(TTilesTests);
end.
