# Generates common/ReforgedVersion.pas -- the SINGLE source of truth for the
# EasyUO Reforged version string, consumed by the title bar, the About box and
# the #ReforgedVer script variable.
#
# Version scheme:  YY.MM.DD.<short git commit>   e.g.  26.09.02.e25a4d9
#   - YY/MM/DD : today's date (local), two digits each
#   - commit   : `git rev-parse --short HEAD`, or "nogit" outside a work tree
#
# This runs automatically before every build (wired into each .lpi as an
# "Execute Before" command) and again in CI, so the version never needs to be
# touched by hand. The generated file is git-ignored; it is rewritten only when
# the value actually changes, so incremental builds stay fast.

$ErrorActionPreference = 'Stop'

$RepoRoot = Split-Path $PSScriptRoot -Parent
$OutFile  = Join-Path $RepoRoot 'common\ReforgedVersion.pas'

$date = (Get-Date).ToString('yy.MM.dd')

$commit = 'nogit'
try {
  $c = & git -C $RepoRoot rev-parse --short HEAD 2>$null
  if ($LASTEXITCODE -eq 0 -and $c) { $commit = $c.Trim() }
} catch {
  # git not installed / not a repo -- fall through to "nogit"
}

$version = "$date.$commit"

$content = @"
unit ReforgedVersion;

{ AUTO-GENERATED by tools\gen-version.ps1 before each build.
  Do not edit, and do not commit -- this file is in .gitignore. }

{`$mode objfpc}{`$H+}

interface

const
  REFORGED_VERSION = '$version';

implementation

end.
"@

$existing = if (Test-Path $OutFile) { Get-Content -Raw -Path $OutFile } else { '' }
if ($existing -ne $content) {
  Set-Content -Path $OutFile -Value $content -Encoding ascii -NoNewline
  Write-Host "gen-version: $version"
} else {
  Write-Host "gen-version: $version (unchanged)"
}
